### ISSUE TITLE
Team Neutral Tracker

### ISSUE THREAD

**Issue by startailcoon** [startailcoon/Gridcoinstats-IssuesTracker#13]
**Implementation of Team Neutral**

This issue is a tracker to implement team neutrality to the stats page.

Tasks

- [ ] Collect data for all teams
- [ ] Present data for all teams
- [ ] Team vs Team comparison
- [ ] Estimated reward, if joining team Gridcoin (until true team neutrality)
